### ISSUE TITLE
보관한 아이템 삭제 기능 제거

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#15]
삭제를 하게 될 시 재고에 영향이 있을 수 밖에 없습니다.
삭제 = 회수 가 아니기 때문입니다.

굳이 아이템을 삭제 할 필요성이 있는지 의문이 듭니다.

**Comment by wookho** [comment]
기간이 만료된 것은 삭제가 필요하던데요.....?

**Comment by Jobdeok** [comment]
@wookho 기록으로 사용할 거라서요. 삭제가 필요없다고 봅니다.

**Comment by bjrambo** [comment]
이 기능에 대한 제 생각은 이 기능을 사용하는 사람에게 굳이 삭제를 없애서 난감하게 만들 필요는 없어보입니다.

각 스킨에서 해당 버튼을 노출하거나 제거 할 수 있도록 하시는게 좋을 것 같습니다.

아니면 모듈 클라이언트안에 옵션을 집어넣어서 삭제기능을 사용할건지 아닌지를 결정하여 해당 모듈 설정에서 제어하도록 하는게 좋을듯..

**Comment by Jobdeok** [comment]
고민을 해보았는데 굳이 삭제를 막을 필요는 없다고 결론을 냈습니다.
삭제시 "해당 아이템에 대한 기록은 삭제되며 복구되지 않습니다" 라고 경고문구를 넣으면 될듯..
