### ISSUE TITLE
다중개설(프로필이미지샵 등) 가능

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#18]
아이콘 외에 프로필이미지 등을 대체하여 쓸 수 있는 샵

- 아이콘샵 외에 프로필이미지샵 및 캐릭터샵으로 활용가능토록 한다.
- #17 이용하여 1개이상의 샵을 생성할 수 있도록 한다.
- 프로필이미지 설정시 회원이 등록한 프로필 이미지는 사용불가 처리된다.
- 기본 기능은 아이콘샵과 동일하다.
- 스킨에서 아이템이 출력되는 코드를 개별로 설정가능하다. (중복방지)

해당 기능은 개발 우선순위를 낮게 둔다.

**Comment by bjrambo** [comment]
운영계획은 글쎄요..

**Comment by Jobdeok** [comment]
@bjrambo 그래서 빼라고 한거..
