### ISSUE TITLE
재고(수량) 표시 개선

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#2]
아이콘 판매 수량이 99개라고 가정하였을때
가지고 있는 아이콘을 판매하는 경우 재고로 잡히지 않습니다.
(99개에서 100개로 변경해야 하지만 99개로 판매됨)

해당 유저의 아이콘이 판매되거나 사용기간 만료시 재고로 잡힐 수 있도록 개선해야 합니다.
또한 아이콘 리스트에서 " 재고수량 / 총수량 " 으로 표시되어야 한다고 봅니다.

예)
A아이콘 100개로 등록
한 유저가 1개 구매 - A아이콘 99 / 100 으로 표기
유저가 아이콘 판매 or 사용기간 만료 - A아이콘 100 / 100 으로 표기

**Comment by bjrambo** [comment]
fixed https://github.com/bjrambo/rx-iconshop/commit/fe92e01e3c82f45a70dfa52a0172e6f384e18a2e
