### ISSUE TITLE
회원상품 추가 제거

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#21]
- 개인의 자유의사를 침해할 소지가 있는 점
- 무분별한 남용으로 인해 특혜로 보일 수가 있는 점
- 포인트 활성화에 도움이 되지 않는 점

위의 사유를 들어 제거해야 한다고 봅니다.

**Comment by bjrambo** [comment]
fixed dac3d1cbe986666bc1bc0a94e31ad78bf6278a87
