### ISSUE TITLE
아이콘 대표설정 해지 ? 가 필요할 수 있습니다.

### ISSUE THREAD

**Issue by wookho** [bjrambo/rx-iconshop#24]
기간이 무제한인 아이콘을 가지고 있다고 가정합니다.

그리고 그 아이콘을 대표로 설정하면 이후 대표설정 해지를 할 수 없습니다.
기능이 존재하지 않아서 이죠.

편법으로 보이지 않는 아이콘을 등록해서 그것을 무료로 구입하게 해서 아이콘을 해지한 것 처럼 보이게 한다는 글을 보았습니다.

물론 아이콘을 삭제하면 되겠지만.....  삭제를 하면 안되는 아이콘일 수 있습니다 사이트에 따라서...
기간 한정으로 판매했다거나... 수량 한정으로 판매를 했던 아이콘이라 가지고는 있어야 하고 잠시 대표설정을 해지해서 아이콘을 잠시 안보이게 할 때도 있고 등등이요...

**Comment by Jobdeok** [comment]
#14 에 해지기능 개선요청 되어 있습니다.
