### ISSUE TITLE
불필요한 상품 기능 제거

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#3]
![default](https://user-images.githubusercontent.com/5928763/27260459-c70e4d24-5467-11e7-9f1e-40865facea90.jpg)

**상품추가에 불필요한 옵션**
1. 판매제한 / 구입제한 : 상품수량 0(품절) 동일
2. 포인트차감 : 상품가격 0(무료) 동일
3. 시간제한 : #4 적용으로 인한 제거
4. 이벤트제한
- 특정일에만 구매가능토록 하는 기능
- 검색의 제한성, 특정일에 해당 아이콘이 맨 상단에 출력되어야 쓸 수 있는 불편함
- 많이 쓰지 않는 기능

5. 레벨제한
- 레벨보다는 그룹이 사용편의성이 좋다고 생각함
- 레벨, 그룹 둘중 하나만 사용해야 한다고 봅니다.

6. 설명 : 쓰지 않는 기능이며 스킨에도 쓰이지 않음
7. 선물제한 : 그룹제한으로 충분하다고 생각

**상품추가에 필요한 옵션**
- 상품이름
- 상품수량
- 상품가격(결제 기간 무료 체크 옵션, 체크시 무료, 체크해제 시 통합설정에 따름)
- 그룹제한
- 첨부파일

**Comment by bjrambo** [comment]
기존의 옵션에서 제거하거 추가하는것은 조금 애매할 것 같고... 어디에서든지 쓰는경우가 있기 때문에 필수조건으로 할 부분만 다듬으면 될 것 같아요.

**Comment by bjrambo** [comment]
여기에는 나중에 확장성을 위한 부분으로 extra_var 디비칼럼을 추가하는 것으로 마무리 할께요 !

**Comment by bjrambo** [comment]
fixed 8fd4de74c65e13163a285eb06d1731b7429a4f5f , de59814043d650cbf4305a3b15a3afcfcba1760d , 49319f686b61d911823b47276c50d6ec6a813432 , 65afc20c018145c98ba80feb241fdef3901748ac , f542afcf0d4e9d1934d9e4f7f70bd25c751cee33
