### ISSUE TITLE
사용기간 기능 추가 및 설정

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#4]
![default](https://user-images.githubusercontent.com/5928763/27258947-e55c90b2-5442-11e7-8043-bfefc9c26943.jpg)
구매/선물 페이지

![default](https://user-images.githubusercontent.com/5928763/27258958-0664a6aa-5443-11e7-91c2-b39b3a015955.jpg)
샵 설정 페이지

< 사용기간 선택 >

상품 가격 외에 사용기간에 따른 포인트를 두도록한다.

< 샵 설정 >

각 상품별로 기간을 개별 설정을 아니하고 통합으로 조정하여 관리토록 합니다.

1. 통합 옵션
- 기간 설정에 따른 포인트는 관리자가 설정토록 한다.
- 아이콘 개별 기간설정은 없다. (무제한 무료/유료 설정만 가능)
- 기간은 00일로 설정한다. (10, 100, 365, 0)

2. 무제한 옵션
- 기간 무제한 무료 옵션을 두는 이유는 상품가격만 필요로 하는 경우 or  상품은 무료 기간은 유료
- '무제한 무료' 체크옵션(체크 일 경우 무료, 해제할 경우 유료)
- 통합설정 부분과 개별 상품설정으로 나눈다.
- 개별 상품에 '무제한 무료' 옵션을 두어 개별 설정이 가능토록 한다. (기본은 통합설정을 따른다)
- 기간 무제한은 무료일 수도 있고 유료일 수도 있다.
- 기간 무제한이 무료로 설정 되었을 시에 추가된 기간에 따른 포인트는 적용되지 않는다.
- 기간 무제한이 무료로 설정 되었을 시 개별 '무제한 무료' 옵션이 나오지 않는다.
- 개별 설정시에 '무제한 무료' 체크 시 통합이 유료로 설정되어 있다하더라도 무료로 설정된다.
- 무제한 포인트 입력창 옆에 체크옵션을 두어 체크 비활성화시에 포인트 입력 INPUT부분을 비활성화한다.
- 기간 무제한이 유료일 경우 추가 기간 포인트보다 낮게 설정되지 않도록 한다.

시나리오1)
'기간 제한 포인트 설정'
- 무제한(기본) : 1000P (무제한 무료 체크)
- 100일 : 100P
- 365일 : 365P

무제한 무료에 체크가 되어 있으므로 100일, 365일 등 기간에 따른 포인트는 적용되지 않는다.

시나리오2)
'기간 제한 포인트 설정'
- 무제한(기본) : 1000P (무제한 무료 체크해제)
- 100일 : 100P
- 365일 : 365P

무제한 무료 체크해제가 되어 있으므로 100일, 365일에 대한 기간 옵션이 적용된다.

3. 사용기간 사용옵션
- 구매일 기준으로 사용기간 책정 or 사용시작 기준으로 사용기간 책정

**Comment by bjrambo** [comment]
추가적으로 선물이나 그런쪽에도 적용해야함 아직~~
