### ISSUE TITLE
아이콘 출력 부분 스킨 코드 제공

### ISSUE THREAD

**Issue by Jobdeok** [bjrambo/rx-iconshop#5]
아이콘샵은 확장시키면 아이콘 뿐만 아니라 프로필 이미지를 상품화하여 판매할 수 있습니다.
그리하여 원하는 위치에 코드를 넣어 아이콘이 출력될 수 있도록 해야 한다고 봅니다.

스킨을 제작함에 있어 아이콘이 정상적인 위치에 출력되도록 조정 할 수 있어야 합니다.
레이아웃이나 게시판 스킨의 스타일로 인해 비정상적인 위치에 노출이 될 경우가 많습니다.

{$symbol} 과 같은 코드를 제공해야 한다고 봅니다.

또한 스킨제작을 어려워하는 분들을 위해 위의 기능을 자동/수동으로 나눠서 설정해야한다고 봅니다.

- 아이콘 출력 설정 : 자동 / 수동(수동 설정시 코드를 넣어야 합니다)
- 프로필 이미지 대체 설정(아이콘 출력 설정 - 수동 선택시)

**Comment by bjrambo** [comment]
일단한번더 검토하겠지만..  일반적으로 엉청난치환으로 구현되는 아이콘들에대해 스킨을지원하는 범위가 불가능해질수 있어요

**Comment by Jobdeok** [comment]
@bjrambo 그렇다면 해당 아이콘 이미지에 클래스명을 두어 CSS로 조정할 수 있게 처리가 제일 좋겠네요.
